# BACKGROUND: Monokai Retro
background=#272822
foreground=#f8f8f2

# CURSOR: Monokai Cursor
cursor=#f8f8f0

# COLOR 0: Black / Dark Grey
color0=#272822
color8=#75715e

# COLOR 1: RED (Monokai Pink/Red)
color1=#f92672
color9=#f92672

# COLOR 2: GREEN (Monokai Green)
color2=#a6e22e
color10=#a6e22e

# COLOR 3: YELLOW (Monokai Yellow)
color3=#e6db74
color11=#e6db74

# COLOR 4: BLUE (Monokai Blue)
color4=#66d9ef
color12=#66d9ef

# COLOR 5: MAGENTA (Monokai Purple)
color5=#ae81ff
color13=#ae81ff

# COLOR 6: CYAN (Monokai Light Blue)
color6=#a1efe4
color14=#a1efe4

# COLOR 7: WHITE (Monokai White)
color7=#f8f8f2
color15=#f9f8f5
