# BACKGROUND: Catppuccin Mocha Dark
background=#1e1e2e
foreground=#cdd6f4

# CURSOR: Catppuccin Rosewater
cursor=#f5e0dc

# COLOR 0: Black
color0=#45475a
color8=#585b70

# COLOR 1: Red
color1=#f38ba8
color9=#f38ba8

# COLOR 2: Green
color2=#a6e3a1
color10=#a6e3a1

# COLOR 3: Yellow
color3=#f9e2af
color11=#f9e2af

# COLOR 4: Blue
color4=#89b4fa
color12=#89b4fa

# COLOR 5: Magenta
color5=#f5c2e7
color13=#f5c2e7

# COLOR 6: Cyan
color6=#94e2d5
color14=#94e2d5

# COLOR 7: White
color7=#bac2de
color15=#a6adc8
