# BACKGROUND: Ayu Dark Slate
background=#0f1419
foreground=#e6b450

# CURSOR: Ayu Orange
cursor=#f29718

# COLOR 0: Black
color0=#000000
color8=#475266

# COLOR 1: Red
color1=#ff3333
color9=#ff6666

# COLOR 2: Green
color2=#c2d94c
color10=#dbe66f

# COLOR 3: Yellow
color3=#f29718
color11=#e6b450

# COLOR 4: Blue
color4=#39bae6
color12=#59c2ff

# COLOR 5: Magenta
color5=#ff7733
color13=#ff9966

# COLOR 6: Cyan
color6=#4cbf99
color14=#95e6cb

# COLOR 7: White
color7=#ffffff
color15=#ffffff
