# BACKGROUND: Tokyo Night Deep Blue
background=#1a1b26
foreground=#a9b1d6

# CURSOR: Tokyo Night Light Blue
cursor=#c0caf5

# COLOR 0: Black
color0=#1d202f
color8=#414868

# COLOR 1: Red
color1=#f7768e
color9=#f7768e

# COLOR 2: Green
color2=#9ece6a
color10=#9ece6a

# COLOR 3: Yellow
color3=#e0af68
color11=#e0af68

# COLOR 4: Blue
color4=#7aa2f7
color12=#7aa2f7

# COLOR 5: Magenta
color5=#bb9af7
color13=#bb9af7

# COLOR 6: Cyan
color6=#7dcfff
color14=#7dcfff

# COLOR 7: White
color7=#a9b1d6
color15=#c0caf5
