# BACKGROUND: Dracula Dark
background=#282a36
foreground=#f8f8f2

# CURSOR: Dracula White
cursor=#f8f8f0

# COLOR 0: Black / Dark Grey
color0=#21222c
color8=#6272a4

# COLOR 1: RED
color1=#ff5555
color9=#ff6e6e

# COLOR 2: GREEN
color2=#50fa7b
color10=#69ff94

# COLOR 3: YELLOW
color3=#f1fa8c
color11=#ffffa5

# COLOR 4: BLUE (Dracula Purple)
color4=#bd93f9
color12=#d6acff

# COLOR 5: MAGENTA (Dracula Pink)
color5=#ff79c6
color13=#ff92df

# COLOR 6: CYAN
color6=#8be9fd
color14=#a4ffff

# COLOR 7: WHITE
color7=#f8f8f2
color15=#ffffff
