# BACKGROUND: Solarized Dark
background=#002b36
foreground=#839496

# CURSOR: Solarized Cursor
cursor=#839496

# COLOR 0: Black / Solarized Base02
color0=#073642
color8=#002b36

# COLOR 1: RED (Solarized Red)
color1=#dc322f
color9=#cb4b16

# COLOR 2: GREEN (Solarized Green)
color2=#859900
color10=#586e75

# COLOR 3: YELLOW (Solarized Yellow)
color3=#b58900
color11=#657b83

# COLOR 4: BLUE (Solarized Blue)
color4=#268bd2
color12=#839496

# COLOR 5: MAGENTA (Solarized Magenta)
color5=#d33682
color13=#6c71c4

# COLOR 6: CYAN (Solarized Cyan)
color6=#2aa198
color14=#93a1a1

# COLOR 7: WHITE (Solarized White)
color7=#eee8d5
color15=#fdf6e3
