# BACKGROUND: Nord Ice-Dark
background=#2e3440
foreground=#d8dee9

# CURSOR: Nord Snow Storm
cursor=#d8dee9

# COLOR 0: Black / Nord Polar Night
color0=#3b4252
color8=#4c566a

# COLOR 1: RED (Nord Aurora Red)
color1=#bf616a
color9=#bf616a

# COLOR 2: GREEN (Nord Aurora Green)
color2=#a3be8c
color10=#a3be8c

# COLOR 3: YELLOW (Nord Aurora Yellow)
color3=#ebcb8b
color11=#ebcb8b

# COLOR 4: BLUE (Nord Frost Blue)
color4=#81a1c1
color12=#81a1c1

# COLOR 5: MAGENTA (Nord Aurora Purple)
color5=#b48ead
color13=#b48ead

# COLOR 6: CYAN (Nord Frost Cyan)
color6=#88c0d0
color14=#8fbcbb

# COLOR 7: WHITE (Nord Snow Storm)
color7=#e5e9f0
color15=#eceff4
