# BACKGROUND: Cobalt2 Blue
background=#132738
foreground=#ffffff

# CURSOR: Cobalt2 Yellow
cursor=#f0cc00

# COLOR 0: Black
color0=#000000
color8=#555555

# COLOR 1: Red
color1=#ff0000
color9=#f43e5c

# COLOR 2: Green
color2=#38de21
color10=#3af820

# COLOR 3: Yellow
color3=#ffe50a
color11=#ff9e3b

# COLOR 4: Blue
color4=#1460d2
color12=#2af7ae

# COLOR 5: Magenta
color5=#ff005d
color13=#ff358b

# COLOR 6: Cyan
color6=#00bbbb
color14=#00e5e5

# COLOR 7: White
color7=#bbbbbb
color15=#ffffff
